const questions=[
{category:"BOLSA FAMÍLIA",question:"Qual lei instituiu o Programa Bolsa Família em sua nova versão, em 2023?",options:["Lei nº 14.601/2023","Lei nº 15.077/2024","Lei nº 14.133/2021","Lei nº 13.709/2018"],answer:0,explanation:"A Lei nº 14.601, de 19 de junho de 2023, instituiu o Programa Bolsa Família."},
{category:"HABITAÇÃO",question:"Em 2023, qual programa habitacional foi recriado por lei durante o governo Lula?",options:["Casa Verde e Amarela","Minha Casa, Minha Vida","PAC Habitação","Programa Nacional de Aluguel"],answer:1,explanation:"O Minha Casa, Minha Vida foi recriado em 2023 pela Lei nº 14.620."},
{category:"CONSTITUIÇÃO",question:"Qual é a principal função da Constituição Federal de 1988 no sistema jurídico brasileiro?",options:["Definir somente impostos federais","Estabelecer a estrutura e os direitos fundamentais do Estado brasileiro","Regular apenas contratos privados","Definir somente regras eleitorais"],answer:1,explanation:"A Constituição organiza o Estado, define competências e estabelece direitos e garantias fundamentais, entre outras matérias."},
{category:"POLÍTICA TRIBUTÁRIA",question:"A reforma tributária aprovada em 2023 alterou principalmente qual área?",options:["Sistema de tributação sobre o consumo","Regras de aposentadoria dos servidores","Sistema eleitoral municipal","Código de trânsito"],answer:0,explanation:"A Emenda Constitucional 132/2023 reformou a tributação sobre o consumo e criou bases para IBS, CBS e Imposto Seletivo, posteriormente regulamentadas."},
{category:"POLÍTICAS SOCIAIS",question:"Qual destas medidas foi apresentada pelo governo federal em 2023 como parte da retomada de políticas públicas?",options:["Desenrola Brasil","Plano Real","Lei da Anistia","Plano Cruzado"],answer:0,explanation:"O Desenrola Brasil foi lançado em 2023 para renegociação de dívidas, integrando o conjunto de políticas econômicas e sociais daquele período."},
{category:"SAÚDE",question:"Qual programa federal foi retomado em 2023 e oferece medicamentos gratuitos ou subsidiados por meio de farmácias credenciadas?",options:["Farmácia Popular","Mais Médicos Escolas","Saúde Brasil 2030","Brasil Sorridente 2"],answer:0,explanation:"O Farmácia Popular foi ampliado em 2023, com medicamentos gratuitos e itens subsidiados conforme as regras do programa."},
{category:"MEIO AMBIENTE",question:"Qual programa criado em 2025 busca estimular investimentos relacionados à transição energética?",options:["Paten","ProUni","Pronampe","Pé-de-Meia"],answer:0,explanation:"A Lei nº 15.103/2025 instituiu o Programa de Aceleração da Transição Energética (Paten)."},
{category:"ASSISTÊNCIA SOCIAL",question:"A Lei nº 15.077/2024 alterou, entre outras normas, a legislação do:",options:["Bolsa Família","Código de Trânsito Brasileiro","Marco Civil da Internet","Estatuto do Torcedor"],answer:0,explanation:"A Lei nº 15.077/2024 alterou leis relacionadas a políticas públicas, incluindo a Lei do Bolsa Família."},
{category:"PROCESSO LEGISLATIVO",question:"No Brasil, qual instituição participa da elaboração das leis federais junto com a Câmara dos Deputados?",options:["Senado Federal","Tribunal de Contas da União","Supremo Tribunal Federal","Banco Central"],answer:0,explanation:"Câmara dos Deputados e Senado Federal compõem o Congresso Nacional e exercem o Poder Legislativo federal."},
{category:"FONTES OFICIAIS",question:"Onde você pode conferir o texto oficial de uma lei federal sancionada?",options:["Portal da Legislação/Planalto e Diário Oficial da União","Somente redes sociais","Somente jornais estrangeiros","Somente blogs políticos"],answer:0,explanation:"Portais oficiais, como o Portal da Legislação da Presidência e o Diário Oficial da União, permitem consultar textos e atos normativos."}
];
let current=0,score=0,locked=false;
const $=id=>document.getElementById(id),hero=$("hero"),quiz=$("quizSection"),result=$("resultSection"),paywall=$("paywall");
$("startBtn").onclick=()=>{hero.classList.add("hidden");quiz.classList.remove("hidden");renderQuestion();scrollTo({top:0,behavior:"smooth"});};
function renderQuestion(){locked=false;const q=questions[current];$("questionNumber").textContent="Pergunta "+String(current+1).padStart(2,"0");$("progressText").textContent=(current+1)+"/"+questions.length;$("progressBar").style.width=((current+1)/questions.length*100)+"%";$("category").textContent=q.category;$("question").textContent=q.question;$("feedback").textContent="";$("feedback").className="";$("nextBtn").disabled=true;$("nextBtn").textContent=current===questions.length-1?"VER MEU RESULTADO →":"CONTINUAR →";$("options").innerHTML="";q.options.forEach((opt,i)=>{const b=document.createElement("button");b.className="option";b.innerHTML="<b>"+String.fromCharCode(65+i)+"</b>"+opt;b.onclick=()=>choose(i);$("options").appendChild(b);});}
function choose(index){if(locked)return;locked=true;const q=questions[current];document.querySelectorAll(".option").forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");if(i===index&&i!==q.answer)b.classList.add("wrong");});if(index===q.answer){score++;$("feedback").textContent="Acertou. "+q.explanation;$("feedback").className="good";}else{$("feedback").textContent="Resposta correta: "+q.options[q.answer]+". "+q.explanation;$("feedback").className="bad";}$("nextBtn").disabled=false;}
$("nextBtn").onclick=()=>{if(!locked)return;current++;if(current<questions.length)renderQuestion();else showResult();};
function showResult(){quiz.classList.add("hidden");result.classList.remove("hidden");$("score").textContent=score;let title="Você concluiu o desafio.";if(score>=8)title="Você conhece bastante do tema.";else if(score>=5)title="Você já tem uma boa base.";else title="Tem muita coisa para descobrir.";$("resultTitle").textContent=title;$("resultText").textContent="Você acertou "+score+" de "+questions.length+". O quiz cobre fatos introdutórios; a área completa organiza mais contexto, legislação e fontes para estudo.";scrollTo({top:0,behavior:"smooth"});}
$("unlockBtn").onclick=()=>{result.classList.add("hidden");paywall.classList.remove("hidden");scrollTo({top:0,behavior:"smooth"});};
$("restartBtn").onclick=()=>{current=0;score=0;result.classList.add("hidden");quiz.classList.remove("hidden");renderQuestion();scrollTo({top:0,behavior:"smooth"});};
$("checkoutBtn").onclick=()=>showToast("Checkout ainda não conectado. Substitua este botão pelo seu link da plataforma de pagamento.");
function showToast(message){const t=$("toast");t.textContent=message;t.classList.remove("hidden");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.add("hidden"),4200);}